[package]
name = "tracing"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
viz = { path = "../../../viz" }

tokio = { version = "1.0", features = [
  "rt-multi-thread",
  "macros",
] }
opentelemetry = "0.18.0"
opentelemetry-jaeger = { version = "0.17.0", features = ["rt-tokio-current-thread"]}
