[package]
name = "markup-template-example"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
vidi.workspace = true

tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }

markup = "0.16"
