[workspace]
members = [
  "viz",
  "viz-core",
  "viz-handlers",
  "viz-macros",
  "viz-router",
  "viz-test",

  "examples/hello-world",
  "examples/unix-socket",
  "examples/static-files/embed",
  "examples/static-files/serve",
  "examples/limits",
  "examples/forms/form",
  "examples/forms/multipart",
  "examples/websocket-chat",
  "examples/sse",
  "examples/session",
  "examples/csrf",
  "examples/cors",
  "examples/rustls",
  "examples/static-routes",
  "examples/routing/todos",
  "examples/routing/openapi",
  "examples/otel/*",
  "examples/compression",
  "examples/templates/*",
  "examples/tracing",
]
resolver = "2"

[workspace.package]
version = "0.5.0-rc.2"
authors = ["Fangdun Tsai <cfddream@gmail.com>"]
edition = "2021"
homepage = "https://viz.rs"
documentation = "https://docs.rs/viz"
repository = "https://github.com/viz-rs/viz"
license = "MIT"

[workspace.dependencies]
viz = { version = "0.5.0-rc.2", path = "viz" }
viz-core = { version = "0.5.0-rc.2", path = "viz-core" }
viz-router = { version = "0.5.0-rc.2", path = "viz-router" }
viz-handlers = { version = "0.5.0-rc.2", path = "viz-handlers", default-features = false }
viz-macros = { version = "0.1.0", path = "viz-macros" }
viz-test = { version = "0.1.0", path = "viz-test" }

async-trait = "0.1.71"
dyn-clone = "1.0.11"
bytes = "1.4.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_urlencoded = "0.7"
thiserror = "1.0"

# router
path-tree = "0.7.1"

# http
headers = "0.3.8"
http = "0.2.9"
http-body = "=1.0.0-rc.2"
http-body-util = "=0.1.0-rc.3"
hyper = { version = "=1.0.0-rc.4", features = ["server"] }

futures-util = "0.3.28"
tokio = { version = "1.29", features = ["net"] }
tokio-tungstenite = "0.19.0"
tokio-stream = "0.1.14"
tokio-util = "0.7.8"
rustls-pemfile = "1.0.3"
tokio-rustls = "0.24.1"
tokio-native-tls = "0.3.1"

anyhow = "1.0"
mime = "0.3.17"
mime_guess = "2.0.4"
percent-encoding = "2.3.0"

hex = "0.4.3"
rust-embed = "6.8.1"

# OpenTelemetry
opentelemetry = { version = "0.19.0", default-features = false }
opentelemetry-prometheus = { version = "0.12.0", features = [
  "prometheus-encoding",
] }
opentelemetry-semantic-conventions = { version = "0.11.0" }

# Tracing
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }

[workspace.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[profile.bench]
debug = true

[profile.dev]
split-debuginfo = "unpacked"

[profile.dev.package."*"]
opt-level = 2
