[package]
name = "multipart-example"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
vidi.workspace = true

futures-util.workspace = true
tokio = { workspace = true, features = [
    "fs",
    "io-util",
    "macros",
    "rt-multi-thread",
] }

tempfile = "3.0"
