[package]
name = "serve-example"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
vidi = { workspace = true, features = ["serve"] }

tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
