[package]
name = "websocket-chat-example"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
vidi = { workspace = true, features = ["websocket"] }

tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros"] }
futures-util.workspace = true
